### PR TITLE
Need Fix Update & build pls look here

### PR DESCRIPTION
**Pull request by himenekocn**

### CODE REVIEW

**Comment by chycken** [comment]
@NapasP please release the new ver of the plugin

**Comment by xLeviNx** [comment]
Did you test this?

**Comment by MatthewNeko** [comment]
> Did you test this?

yep, It has been used for two days already

**Comment by chycken** [comment]
@himenekocn can u send me the compiled new version please?

**Comment by MatthewNeko** [comment]
> @himenekocn can u send me the compiled new version please?

view my git workflow

**Comment by chycken** [comment]
> > @himenekocn can u send me the compiled new version please?
> 
> view my git workflow

thanks dude, downloaded

**Comment by xLeviNx** [comment]
> > Did you test this?
> 
> yep, It has been used for two days already

same color schema? Things like {DARKRED} don't work

**Comment by MatthewNeko** [comment]
> > > Did you test this?
> > 
> > 
> > yep, It has been used for two days already
> 
> same color schema? Things like {DARKRED} don't work

see the code, i have nothing change it

**Comment by Bonusfrag** [comment]
Update pls)

**Comment by MatthewNeko** [comment]
> Update pls)

It has been updated. Do you have any questions?

**Pull request merged**
